/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Pati
 */
public class ingresarVeh extends javax.swing.JFrame {

    /**
     * Creates new form ingresarVeh
     */
    public ingresarVeh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtplaca = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnIngresarVeh = new javax.swing.JButton();
        jcbtipo = new javax.swing.JComboBox<>();
        btnSalirregs = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Propietario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Placa:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Color:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Modelo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, 10));
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 143, -1));
        getContentPane().add(txtplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 143, -1));
        getContentPane().add(txtcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 143, 20));
        getContentPane().add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 143, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tipos de Vehiculos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setText("Registar vehiculos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        BtnIngresarVeh.setBackground(new java.awt.Color(204, 255, 255));
        BtnIngresarVeh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnIngresarVeh.setText("Registrar");
        BtnIngresarVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarVehActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIngresarVeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        jcbtipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eliga la opción", "Vehiculo", "Automovil", "Bicicleta", "Motocicleta" }));
        getContentPane().add(jcbtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 114, -1));

        btnSalirregs.setBackground(new java.awt.Color(204, 255, 204));
        btnSalirregs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalirregs.setText("Salir");
        btnSalirregs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirregsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirregs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 80, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fonu.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarVehActionPerformed
        // TODO add your handling code here:
        Contralador.controladoringresarVeh.BtnIngresarVeh();
    }//GEN-LAST:event_BtnIngresarVehActionPerformed

    private void btnSalirregsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirregsActionPerformed
        // TODO add your handling code here:
        Contralador.controladoringresarVeh.btnSalirregs();
    }//GEN-LAST:event_btnSalirregsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresarVeh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresarVeh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresarVeh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresarVeh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingresarVeh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnIngresarVeh;
    private javax.swing.JButton btnSalirregs;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JComboBox<String> jcbtipo;
    public javax.swing.JTextField txtcolor;
    public javax.swing.JTextField txtmodelo;
    public javax.swing.JTextField txtplaca;
    public javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
