/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Contralador.controladorinicio;

/**
 *
 * @author Pati
 */
public class inicio extends javax.swing.JFrame {
   
    
  
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrinIngresarAdmin = new javax.swing.JButton();
        Com = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPrinIngresar = new javax.swing.JButton();
        Administrador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrinIngresarAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnPrinIngresarAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrinIngresarAdmin.setForeground(new java.awt.Color(51, 51, 0));
        btnPrinIngresarAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgusuario.png"))); // NOI18N
        btnPrinIngresarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrinIngresarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrinIngresarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrinIngresarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 170, 200));

        Com.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Com.setText("INGRESE AL LOGIN CORRESPONDIDO");
        getContentPane().add(Com, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Usuario ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        btnPrinIngresar.setBackground(new java.awt.Color(255, 255, 255));
        btnPrinIngresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrinIngresar.setForeground(new java.awt.Color(51, 51, 0));
        btnPrinIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuaq.jpg"))); // NOI18N
        btnPrinIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrinIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrinIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrinIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 250, 190));

        Administrador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Administrador.setText("Administrador ");
        getContentPane().add(Administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pantalla.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrinIngresarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrinIngresarAdminActionPerformed
        // TODO add your handling code here
        controladorinicio.btnPrinIngresarAdmin();
     
    }//GEN-LAST:event_btnPrinIngresarAdminActionPerformed

    private void btnPrinIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrinIngresarActionPerformed
        // TODO add your handling code here:
        controladorinicio.btnPrinIngresar();

    }//GEN-LAST:event_btnPrinIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Administrador;
    private javax.swing.JLabel Com;
    public javax.swing.JButton btnPrinIngresar;
    public javax.swing.JButton btnPrinIngresarAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
