/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Pati
 */
public class logiAdm extends javax.swing.JFrame {

    /**
     * Creates new form logiAdm
     */
    public logiAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAusuario = new javax.swing.JTextField();
        txtAPass = new javax.swing.JPasswordField();
        btnAdminlog = new javax.swing.JButton();
        Administrador = new javax.swing.JLabel();
        btnregistrarAdmin = new javax.swing.JButton();
        ima = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Usuarios:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PassWord:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        txtAusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtAusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, -1));
        getContentPane().add(txtAPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 150, -1));

        btnAdminlog.setBackground(new java.awt.Color(204, 255, 255));
        btnAdminlog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdminlog.setText("Iniciar Sesión");
        btnAdminlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminlogActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdminlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 120, -1));

        Administrador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Administrador.setForeground(new java.awt.Color(0, 0, 102));
        Administrador.setText("**   Administrador  **");
        getContentPane().add(Administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        btnregistrarAdmin.setBackground(new java.awt.Color(0, 204, 204));
        btnregistrarAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnregistrarAdmin.setForeground(new java.awt.Color(0, 51, 51));
        btnregistrarAdmin.setText("crear cuenta nueva");
        btnregistrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        ima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgusuario.png"))); // NOI18N
        getContentPane().add(ima, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/go0.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 340, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/p098.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAusuarioActionPerformed

    private void btnAdminlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminlogActionPerformed
        // TODO add your handling code here:
        Contralador.controladorlogiAdmin.btnAdminlog();
    }//GEN-LAST:event_btnAdminlogActionPerformed

    private void btnregistrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarAdminActionPerformed
        // TODO add your handling code here:
        
         Contralador.controladorlogiAdmin.btnGuardarAdmin();
    }//GEN-LAST:event_btnregistrarAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logiAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logiAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logiAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logiAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logiAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Administrador;
    public javax.swing.JButton btnAdminlog;
    private javax.swing.JButton btnregistrarAdmin;
    private javax.swing.JLabel ima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPasswordField txtAPass;
    public javax.swing.JTextField txtAusuario;
    // End of variables declaration//GEN-END:variables
}
